//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPWMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorisation
    {
        public int AuthorisationId { get; set; }
        public string User_Name { get; set; }
        public string User_Password { get; set; }
        public int Company { get; set; }
        public int User { get; set; }
        public string User_Section_Code { get; set; }
        public double User_Approval_Limit { get; set; }
        public Nullable<int> WorkId { get; set; }
    
        public virtual Work Work { get; set; }
    }
}
