//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPWMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public int BuildingId { get; set; }
        public string OPW_Building_Code { get; set; }
        public string Address { get; set; }
        public string County { get; set; }
        public int B_Type { get; set; }
        public string Cost_Centre { get; set; }
        public int B_Team { get; set; }
        public Nullable<int> WorkId { get; set; }
    
        public virtual Work Work { get; set; }
    }
}
